name: Deploy Conference Management System Backend to GCP VM

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Pull code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2️⃣ Login to Docker Hub
      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      # 3️⃣ Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/saraconference-backend:latest .

      # 4️⃣ Push Image
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USER }}/saraconference:latest

      # 5️⃣ Deploy to GCP VM via SSH
      - name: Deploy to GCP VM
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            
            echo "🔐 Logging into Docker Hub on VM"
            docker login -u "${{ secrets.DOCKER_USER }}" -p "${{ secrets.DOCKER_PASS }}"
            
            echo "📥 Pulling latest image"
            docker pull ${{ secrets.DOCKER_USER }}/saraconference-backend:latest
            
            echo "stopping old container "
            docker stop saraconference-backend
            docker rm saraconference-backend
            echo "🚀 Starting new container"
            docker run -d \
            --name saraconference \
            -e TZ=Asia/Kolkata \
            -e JAVA_TOOL_OPTIONS="-Duser.timezone=Asia/Kolkata" \
            -e SPRING_PROFILES_ACTIVE="prod"
            --env-file /home/founder_sarasell/saraconference/.env \
            -p 8090:8090 \
            --restart unless-stopped \
            ${{ secrets.DOCKER_USER }}/saraconference-backend:latest

            
            echo "✅ Deployment finished"
