name: Trigger auto deployment for saraconference-backend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/saraconference-backend-AutoDeployTrigger-8c307709-cf43-47f2-8cec-008bfb881bbe.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.SARACONFERENCEBACKEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SARACONFERENCEBACKEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SARACONFERENCEBACKEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: docker.io
          registryUsername: ${{ secrets.SARACONFERENCEBACKEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SARACONFERENCEBACKEND_REGISTRY_PASSWORD }}
          containerAppName: saraconference-backend
          resourceGroup: SaraConference2025
          imageToBuild: stellarstacker/saraconference-backend:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


